export default {
  title: "Better Friend",
  header: "Better Friend",
  addFriendHeader: "Thêm Bạn",
  addFriendBtn: "Thêm Bạn",
  friendDetailHeader: "Thông Tin Của Bạn",
  settingsHeader: "Cài Đặt",
  createProfile: "Tạo Thông Tin",
  changeLayout: "Đổi Bố Cục",
  changeLanguage: "Đổi Ngôn Ngữ",
  changeOrder: "Đổi Thứ Tự",
  exportImportFriends: "Xuất/Nhập Bạn Bè",
  importContacts: "Nhập Thông Tin Liên Lạc",
  changeDescription: "Đổi Mô Tả Mặc Định",
  changeMacOs: "Chế Độ Màn Hình Lớn",
  reportBug: "Báo Cáo Lỗi",
  resetApp: "Reset App",
  redeemCode: "Redeem Code",
  searchInput: "Tìm Bạn...",
  friendNameInput: "Nhập tên của bạn",
  friendNickInput: "Nhập biệt danh của bạn",
  friendTimezoneInput: "Chọn múi giờ của bạn",
  friendBirthdayInput: "Chọn ngày sinh của bạn",
  friendTagsInput: "e.g., đồng nghiệp, gym",
  friendNameLabel: "Tên:",
  friendNickLabel: "Biệt danh:",
  friendTimezoneLabel: "Múi giờ:",
  friendNumberLabel: "Số điện thoại:",
  friendBirthdayLabel: "Sinh nhật:",
  friendMeetdayLabel: "Ngày gặp:",
  friendImageLabel: "Tải hình lên:",
  nowBtn: "Bây giờ",
  friendTagsLabel: "Tags (phân biệt tag bằng dấu phẩy):",
  totalContacts: "Tổng Thông Tin Liên Lạc:",
  permissionDenied: "Không có quyền truy cập",
  unknown: "Unknown",
  noTags: "Không có Tags",
  noNotifications: "Chưa có thông báo.",
  friendNotFound: "Bạn ${FRIEND} không tồn tại, hãy thêm họ vào!",
  friendNotFoundParams: "Không tìm thấy bạn, hãy điều chỉnh thông số tìm kiếm",
  birthday: "Sinh nhật",
  meetday: "Ngày gặp",
  totalContactsSelected: "Tổng thông tin liên lạc đã chọn:",
  alertErrorReset: "Có lỗi xảy ra khi khởi động lại ứng dụng. Hãy thử lại sau.",
  errorLoadNotifications: "Tải thông báo không thành công.",
  modal: {
    deleteNotification: "Xóa thông báo này?",
    missingRequiredInfo: {
      title: "Thiếu Thông Tin Bắt Buộc",
      message: "Vui lòng nhập tên của bạn.",
      confirmText: "Đã hiểu",
    },
    default: {
      title: "Xác Nhận Thao Tác",
      message: "Bạn có chắc sẽ khởi động lại chứ?",
      confirmText: "Đồng ý",
      cancelText: "Hủy",
    },
    revert: {
      title: "Bạn chắc chắn chứ? Mọi cài đặt của bạn sẽ quay về mặc định",
    },
    delete: {
      title: "Xóa cài đặt. Xóa hết mọi thông tin?",
    },
    tags: {
      title: "Chỉnh Sửa Tags",
      description: "Chọn tag để đính kèm với người bạn này.",
      message: "Bạn chắc chắn chứ?",
      confirmText: "Lưu",
      cancelText: "Hủy",
    },
    importContacts: {
      title: "Thêm bạn bè",
      message:
        "Bạn có muốn thêm từ danh bạ không? Bạn luôn có thể truy cập nhập thêm từ danh bạ trong cài đặt.",
      confirmText: "Đồng ý",
      cancelText: "Thêm thủ công",
    },
    deleteFriend: {
      title: "Bạn có chắc chứ? Tất cả thông tin sẽ bị xóa!",
    },
    list: {
      title: "Vui lòng chọn một item:",
      message: "Chọn Item",
      confirmText: "Chọn",
      cancelText: "Hủy",
    },
    langs: {
      title: "Chọn Ngôn Ngữ",
      message: "Chọn ngôn ngữ của bạn:",
      confirmText: "Áp dụng",
      cancelText: "Hủy",
    },
    order: {
      title: "Thay Đổi Thứ Tự",
      message: "Sắp Xếp Bạn Bè Theo:",
      confirmText: "Đồng ý",
      cancelText: "Hủy",
      options: [
        "Tăng dần theo chữ cái",
        "Giảm dần theo chữ cái",
        "Tăng dần theo ngày tạo",
        "Giảm dần theo ngày tạo",
        "Tương tác nhiều nhất",
        "Tương tác ít nhất",
        "Chỉnh sửa cuối cùng",
        "Sinh nhật sắp tới",
        "Ngày gặp sắp tới",
      ],
    },
    orderConfirm: {
      title: "Thay Đổi Thứ Tự",
      message: "Thứ tự đã thay đổi theo",
      confirmText: "OK",
    },
    langConfirm: {
      title: "Thay Đổi Ngôn Ngữ",
      message: "Ngôn ngữ đã được đổi thành",
      confirmText: "OK",
    },
    macOS: {
      title: "Thành công",
      message: "Hệ thống đã thành công thay đổi sang",
      ios: "iOS",
      mac: "macOS",
      confirmText: "OK",
    },
    defaultDesc: {
      title: "Cập Nhật Mô tả",
      message: "Điền mô tả mặc định của bạn này:",
      confirmText: "Lưu",
      cancelText: "Hủy",
    },
    fileUpload: {
      title: "Cập Nhật Mô tả",
      message: "Thay đổi ảnh đại diện của bạn:",
      confirmText: "Tải lên",
      cancelText: "Hủy",
    },
    prompt: {
      title: "Yêu Cầu Thông Tin",
      message: "Vui lòng nhập mã:",
      confirmText: "OK",
      cancelText: "Hủy",
    },
    addNotification: {
      title: "Thêm Thông Báo",
      message: "Thêm thông báo mới cho bạn này",
      confirmText: "Hẹn lịch",
      labels: {
        title: "Tiêu Đề",
        titlePlaceholder: "VD: Gọi trong ngày sinh nhật",
        body: "Thông điệp",
        bodyPlaceholder: "Chi tiết...",
        date: "Ngày & Giờ",
        priority: "Tầm quan trọng",
        repeats: "Lặp lại?",
      },
      priorities: {
        low: "Thấp",
        medium: "Trung bình",
        high: "Cao",
      },
      repeats: {
        no: "Không",
        year: "Hằng năm",
        month: "Hằng tháng",
        week: "Hằng tuần",
        day: "Hằng ngày",
      },
      error: {
        title: "Lỗi",
        message:
          "Hẹn lịch thông báo không thành công. Vui lòng kiểm tra lại ngày.",
      },
    },
    editFriend: {
      title: "Chỉnh Sửa Bạn",
      message: "Cập nhật thông tin bạn bên dưới:",
      labels: {
        name: "Tên",
        nick: "Biệt danh",
        contact: "Số lần tương tác",
        timezone: "Múi giờ",
        birthday: "Ngày sinh",
        meetday: "Ngày gặp",
      },
      placeholders: {
        contact: "@instagram hoặc +55 11 1234-12345",
      },
    },
  },
  "notification-btn": "Thông báo",
  defaultFriendDescription: `*"Bạn tốt giống như cỏ bốn lá vậy; khó mà kiếm được và may mắn khi có được."*\n\n# Nhấn vào đây để chỉnh sửa ghi chú!`,
  dateNotInformed: "Không có ngày",
  noNewContactsFound: "Không có thông tin liên lạc mới",
  contactsError: "Lỗi khi tải thông tin liên lạc",
  timezoneOptions: {
    "-12": "UTC-12: Đảo Baker, Đảo Howland",
    "-11": "UTC-11: Samoa thuộc Mỹ, Niue",
    "-10": "UTC-10: Hawaii, phần lớn Polynesia thuộc Pháp",
    "-9": "UTC-9: Alaska, Quần đảo Gambier (Pháp)",
    "-8": "UTC-8: Múi giờ Thái Bình Dương, Baja California (Mexico)",
    "-7": "UTC-7: Múi giờ miền núi, Sonora (Mexico)",
    "-6": "UTC-6: Múi giờ miền Trung (Bắc Mỹ)",
    "-5": "UTC-5: Múi giờ miền Đông, Cuba, Colombia, Ecuador (đất liền)",
    "-4": "UTC-4: Múi giờ miền Đại Tây Dương (Canada), Venezuela, Bolivia, Chile (đất liền)",
    "-3.5": "UTC-3:30: Newfoundland (Canada)",
    "-3": "UTC-3: Giờ Brasília, Argentina, Uruguay",
    "-2": "UTC-2: Fernando de Noronha (Brazil), Nam Georgia",
    "-1": "UTC-1: Azores (Bồ Đào Nha), Cape Verde",
    0: "UTC+0: Vương quốc Anh, Ireland, Bồ Đào Nha, Iceland, Tây Phi",
    1: "UTC+1: Trung Âu, Giờ Tây Phi",
    2: "UTC+2: Đông Âu, Ai Cập, Nam Phi",
    3: "UTC+3: Nga, Đông Phi, Ả Rập",
    3.5: "UTC+3:30: Iran",
    4: "UTC+4: Các Tiểu vương quốc Ả Rập Thống nhất, Oman, Azerbaijan",
    4.5: "UTC+4:30: Afghanistan",
    5: "UTC+5: Pakistan, Uzbekistan",
    5.5: "UTC+5:30: Ấn Độ, Sri Lanka",
    5.75: "UTC+5:45: Nepal",
    6: "UTC+6: Bangladesh, Bhutan, Kazakhstan",
    6.5: "UTC+6:30: Myanmar, Quần đảo Cocos",
    7: "UTC+7: Thái Lan, Việt Nam, Indonesia",
    8: "UTC+8: Trung Quốc, Philippines, Malaysia, Singapore, Tây Úc",
    9: "UTC+9: Nhật Bản, Hàn Quốc, Đông Indonesia",
    9.5: "UTC+9:30: Nam Úc, Lảnh thổ Bắc Úc (Úc)",
    10: "UTC+10: Queensland, Papua New Guinea",
    10.5: "UTC+10:30: Đảo Lord Howe",
    11: "UTC+11: New Caledonia, Quần đảo Solomon",
    12: "UTC+12: New Zealand, Fiji, Quần đảo Marshall",
    12.75: "UTC+12:45: Quần đảo Chatham",
    13: "UTC+13: Tonga, Samoa, Tokelau",
    14: "UTC+14: Quần đảo Line",
  },
  themeText: "",
  settings: {
    light: "Đổi sang chế độ Sáng",
    dark: "Đổi sang chế độ Tối",
  },
  notifications: {
    meetday: {
      title: "📅 Kỷ Niệm Ngày Gặp",
      body: "Bạn đã là bạn bè của ${nickName} từ năm ${year}!",
    },
    birthday: {
      title: "🎉 Sinh nhật của ${name}!",
      body: "Chúc mừng sinh nhật cho ${nickName}!",
    },
    upcomingBirthday: {
      title: "🎉 Một tuần nữa là sinh nhật của ${name}!",
      body: "Nhớ chuẩn bị cho bạn ấy một món quà!",
    },
    interaction: {
      title: "💭 Nhắc nhở về ${displayName}",
      body: "Đừng quên liên lạc với ${displayName}!",
    },
  },
  sortHeader: "Lựa Chọn Sắp Xếp",
  emptyMessage: "Chưa thêm bạn bè nào. Hãy thêm họ vào!",
  "interaction-btn-disabled": "Thêm Thông Tin Liên Hệ Của Bạn",
};
